micronaut:
  application:
    name: oda-recipient-service
  executors:
    rabbit:
      nThreads: 1
      type: fixed
      name: rabbit
  security:
    token:
      bearer:
        enabled: true
      cookie:
        enabled: true
      jwt:
        signatures:
          jwks:
            keycloak:
              url: https://auth.oda.digital/realms/ODA/protocol/openid-connect/certs
endpoints:
  flyway:
    enabled: true
flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
      validate-migration-naming: false
      validate-on-migrate: false
jpa:
  default:
    entity-scan:
        packages: 'io.github.stcarolas.oda'
rabbitmq:
  host: ${RABBITMQ_HOST:`localhost`}
  consumer-executor: "rabbit"
infinispan:
  client:
    hotrod:
      server:
        host: "${INFINISPAN_HOST: `127.0.0.1`}"
        port: "${INFINISPAN_PORT: 11222}"

